//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SQLiteParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Antlr4C3.Demo.Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISQLiteParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SQLiteParserBaseListener : ISQLiteParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParse([NotNull] SQLiteParser.ParseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParse([NotNull] SQLiteParser.ParseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.sql_stmt_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSql_stmt_list([NotNull] SQLiteParser.Sql_stmt_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.sql_stmt_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSql_stmt_list([NotNull] SQLiteParser.Sql_stmt_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.sql_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSql_stmt([NotNull] SQLiteParser.Sql_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.sql_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSql_stmt([NotNull] SQLiteParser.Sql_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.alter_table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlter_table_stmt([NotNull] SQLiteParser.Alter_table_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.alter_table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlter_table_stmt([NotNull] SQLiteParser.Alter_table_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.analyze_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnalyze_stmt([NotNull] SQLiteParser.Analyze_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.analyze_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnalyze_stmt([NotNull] SQLiteParser.Analyze_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.attach_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttach_stmt([NotNull] SQLiteParser.Attach_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.attach_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttach_stmt([NotNull] SQLiteParser.Attach_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.begin_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBegin_stmt([NotNull] SQLiteParser.Begin_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.begin_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBegin_stmt([NotNull] SQLiteParser.Begin_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.commit_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommit_stmt([NotNull] SQLiteParser.Commit_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.commit_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommit_stmt([NotNull] SQLiteParser.Commit_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.rollback_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRollback_stmt([NotNull] SQLiteParser.Rollback_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.rollback_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRollback_stmt([NotNull] SQLiteParser.Rollback_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.savepoint_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSavepoint_stmt([NotNull] SQLiteParser.Savepoint_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.savepoint_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSavepoint_stmt([NotNull] SQLiteParser.Savepoint_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.release_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelease_stmt([NotNull] SQLiteParser.Release_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.release_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelease_stmt([NotNull] SQLiteParser.Release_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.create_index_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_index_stmt([NotNull] SQLiteParser.Create_index_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.create_index_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_index_stmt([NotNull] SQLiteParser.Create_index_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.indexed_column"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexed_column([NotNull] SQLiteParser.Indexed_columnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.indexed_column"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexed_column([NotNull] SQLiteParser.Indexed_columnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.create_table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_table_stmt([NotNull] SQLiteParser.Create_table_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.create_table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_table_stmt([NotNull] SQLiteParser.Create_table_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.table_options"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_options([NotNull] SQLiteParser.Table_optionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.table_options"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_options([NotNull] SQLiteParser.Table_optionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.column_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_def([NotNull] SQLiteParser.Column_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.column_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_def([NotNull] SQLiteParser.Column_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_name([NotNull] SQLiteParser.Type_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_name([NotNull] SQLiteParser.Type_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.column_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_constraint([NotNull] SQLiteParser.Column_constraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.column_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_constraint([NotNull] SQLiteParser.Column_constraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.signed_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSigned_number([NotNull] SQLiteParser.Signed_numberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.signed_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSigned_number([NotNull] SQLiteParser.Signed_numberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.table_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_constraint([NotNull] SQLiteParser.Table_constraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.table_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_constraint([NotNull] SQLiteParser.Table_constraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.foreign_key_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeign_key_clause([NotNull] SQLiteParser.Foreign_key_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.foreign_key_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeign_key_clause([NotNull] SQLiteParser.Foreign_key_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.conflict_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConflict_clause([NotNull] SQLiteParser.Conflict_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.conflict_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConflict_clause([NotNull] SQLiteParser.Conflict_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.create_trigger_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_trigger_stmt([NotNull] SQLiteParser.Create_trigger_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.create_trigger_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_trigger_stmt([NotNull] SQLiteParser.Create_trigger_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.create_view_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_view_stmt([NotNull] SQLiteParser.Create_view_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.create_view_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_view_stmt([NotNull] SQLiteParser.Create_view_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.create_virtual_table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_virtual_table_stmt([NotNull] SQLiteParser.Create_virtual_table_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.create_virtual_table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_virtual_table_stmt([NotNull] SQLiteParser.Create_virtual_table_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.with_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWith_clause([NotNull] SQLiteParser.With_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.with_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWith_clause([NotNull] SQLiteParser.With_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.common_table_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommon_table_expression([NotNull] SQLiteParser.Common_table_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.common_table_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommon_table_expression([NotNull] SQLiteParser.Common_table_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.cte_table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCte_table_name([NotNull] SQLiteParser.Cte_table_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.cte_table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCte_table_name([NotNull] SQLiteParser.Cte_table_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.delete_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDelete_stmt([NotNull] SQLiteParser.Delete_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.delete_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDelete_stmt([NotNull] SQLiteParser.Delete_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.detach_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDetach_stmt([NotNull] SQLiteParser.Detach_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.detach_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDetach_stmt([NotNull] SQLiteParser.Detach_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.drop_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrop_stmt([NotNull] SQLiteParser.Drop_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.drop_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrop_stmt([NotNull] SQLiteParser.Drop_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] SQLiteParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] SQLiteParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_or([NotNull] SQLiteParser.Expr_orContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_or([NotNull] SQLiteParser.Expr_orContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_and([NotNull] SQLiteParser.Expr_andContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_and([NotNull] SQLiteParser.Expr_andContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_not"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_not([NotNull] SQLiteParser.Expr_notContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_not"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_not([NotNull] SQLiteParser.Expr_notContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_binary([NotNull] SQLiteParser.Expr_binaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_binary([NotNull] SQLiteParser.Expr_binaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_comparison([NotNull] SQLiteParser.Expr_comparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_comparison([NotNull] SQLiteParser.Expr_comparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_bitwise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_bitwise([NotNull] SQLiteParser.Expr_bitwiseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_bitwise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_bitwise([NotNull] SQLiteParser.Expr_bitwiseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_addition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_addition([NotNull] SQLiteParser.Expr_additionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_addition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_addition([NotNull] SQLiteParser.Expr_additionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_multiplication"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_multiplication([NotNull] SQLiteParser.Expr_multiplicationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_multiplication"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_multiplication([NotNull] SQLiteParser.Expr_multiplicationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_string([NotNull] SQLiteParser.Expr_stringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_string([NotNull] SQLiteParser.Expr_stringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_collate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_collate([NotNull] SQLiteParser.Expr_collateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_collate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_collate([NotNull] SQLiteParser.Expr_collateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_unary([NotNull] SQLiteParser.Expr_unaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_unary([NotNull] SQLiteParser.Expr_unaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_base([NotNull] SQLiteParser.Expr_baseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_base([NotNull] SQLiteParser.Expr_baseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.expr_recursive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_recursive([NotNull] SQLiteParser.Expr_recursiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.expr_recursive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_recursive([NotNull] SQLiteParser.Expr_recursiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.raise_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaise_function([NotNull] SQLiteParser.Raise_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.raise_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaise_function([NotNull] SQLiteParser.Raise_functionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.literal_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral_value([NotNull] SQLiteParser.Literal_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.literal_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral_value([NotNull] SQLiteParser.Literal_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.percentile_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPercentile_clause([NotNull] SQLiteParser.Percentile_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.percentile_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPercentile_clause([NotNull] SQLiteParser.Percentile_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.value_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_row([NotNull] SQLiteParser.Value_rowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.value_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_row([NotNull] SQLiteParser.Value_rowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.values_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValues_clause([NotNull] SQLiteParser.Values_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.values_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValues_clause([NotNull] SQLiteParser.Values_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.insert_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInsert_stmt([NotNull] SQLiteParser.Insert_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.insert_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInsert_stmt([NotNull] SQLiteParser.Insert_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.returning_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturning_clause([NotNull] SQLiteParser.Returning_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.returning_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturning_clause([NotNull] SQLiteParser.Returning_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.upsert_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpsert_clause([NotNull] SQLiteParser.Upsert_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.upsert_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpsert_clause([NotNull] SQLiteParser.Upsert_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.pragma_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragma_stmt([NotNull] SQLiteParser.Pragma_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.pragma_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragma_stmt([NotNull] SQLiteParser.Pragma_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.pragma_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragma_value([NotNull] SQLiteParser.Pragma_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.pragma_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragma_value([NotNull] SQLiteParser.Pragma_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.reindex_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReindex_stmt([NotNull] SQLiteParser.Reindex_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.reindex_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReindex_stmt([NotNull] SQLiteParser.Reindex_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.select_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_stmt([NotNull] SQLiteParser.Select_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.select_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_stmt([NotNull] SQLiteParser.Select_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.join_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoin_clause([NotNull] SQLiteParser.Join_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.join_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoin_clause([NotNull] SQLiteParser.Join_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.select_core"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_core([NotNull] SQLiteParser.Select_coreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.select_core"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_core([NotNull] SQLiteParser.Select_coreContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.table_or_subquery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_or_subquery([NotNull] SQLiteParser.Table_or_subqueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.table_or_subquery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_or_subquery([NotNull] SQLiteParser.Table_or_subqueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.result_column"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResult_column([NotNull] SQLiteParser.Result_columnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.result_column"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResult_column([NotNull] SQLiteParser.Result_columnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.join_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoin_operator([NotNull] SQLiteParser.Join_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.join_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoin_operator([NotNull] SQLiteParser.Join_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.join_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoin_constraint([NotNull] SQLiteParser.Join_constraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.join_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoin_constraint([NotNull] SQLiteParser.Join_constraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.compound_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompound_operator([NotNull] SQLiteParser.Compound_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.compound_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompound_operator([NotNull] SQLiteParser.Compound_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.update_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpdate_stmt([NotNull] SQLiteParser.Update_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.update_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpdate_stmt([NotNull] SQLiteParser.Update_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.column_name_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_name_list([NotNull] SQLiteParser.Column_name_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.column_name_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_name_list([NotNull] SQLiteParser.Column_name_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.qualified_table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualified_table_name([NotNull] SQLiteParser.Qualified_table_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.qualified_table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualified_table_name([NotNull] SQLiteParser.Qualified_table_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.vacuum_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVacuum_stmt([NotNull] SQLiteParser.Vacuum_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.vacuum_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVacuum_stmt([NotNull] SQLiteParser.Vacuum_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.filter_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilter_clause([NotNull] SQLiteParser.Filter_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.filter_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilter_clause([NotNull] SQLiteParser.Filter_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.window_defn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWindow_defn([NotNull] SQLiteParser.Window_defnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.window_defn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWindow_defn([NotNull] SQLiteParser.Window_defnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.over_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOver_clause([NotNull] SQLiteParser.Over_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.over_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOver_clause([NotNull] SQLiteParser.Over_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.frame_spec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrame_spec([NotNull] SQLiteParser.Frame_specContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.frame_spec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrame_spec([NotNull] SQLiteParser.Frame_specContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.frame_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrame_clause([NotNull] SQLiteParser.Frame_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.frame_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrame_clause([NotNull] SQLiteParser.Frame_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.order_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrder_clause([NotNull] SQLiteParser.Order_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.order_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrder_clause([NotNull] SQLiteParser.Order_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.limit_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLimit_clause([NotNull] SQLiteParser.Limit_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.limit_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLimit_clause([NotNull] SQLiteParser.Limit_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.ordering_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrdering_term([NotNull] SQLiteParser.Ordering_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.ordering_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrdering_term([NotNull] SQLiteParser.Ordering_termContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.asc_desc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsc_desc([NotNull] SQLiteParser.Asc_descContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.asc_desc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsc_desc([NotNull] SQLiteParser.Asc_descContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.frame_left"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrame_left([NotNull] SQLiteParser.Frame_leftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.frame_left"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrame_left([NotNull] SQLiteParser.Frame_leftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.frame_right"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrame_right([NotNull] SQLiteParser.Frame_rightContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.frame_right"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrame_right([NotNull] SQLiteParser.Frame_rightContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.frame_single"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrame_single([NotNull] SQLiteParser.Frame_singleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.frame_single"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrame_single([NotNull] SQLiteParser.Frame_singleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.error_message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterError_message([NotNull] SQLiteParser.Error_messageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.error_message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitError_message([NotNull] SQLiteParser.Error_messageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.filename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilename([NotNull] SQLiteParser.FilenameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.filename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilename([NotNull] SQLiteParser.FilenameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.module_argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule_argument([NotNull] SQLiteParser.Module_argumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.module_argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule_argument([NotNull] SQLiteParser.Module_argumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.module_argument_outer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule_argument_outer([NotNull] SQLiteParser.Module_argument_outerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.module_argument_outer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule_argument_outer([NotNull] SQLiteParser.Module_argument_outerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.module_argument_inner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule_argument_inner([NotNull] SQLiteParser.Module_argument_innerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.module_argument_inner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule_argument_inner([NotNull] SQLiteParser.Module_argument_innerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.fallback_excluding_conflicts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFallback_excluding_conflicts([NotNull] SQLiteParser.Fallback_excluding_conflictsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.fallback_excluding_conflicts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFallback_excluding_conflicts([NotNull] SQLiteParser.Fallback_excluding_conflictsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.join_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoin_keyword([NotNull] SQLiteParser.Join_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.join_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoin_keyword([NotNull] SQLiteParser.Join_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.fallback"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFallback([NotNull] SQLiteParser.FallbackContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.fallback"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFallback([NotNull] SQLiteParser.FallbackContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] SQLiteParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] SQLiteParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_name([NotNull] SQLiteParser.Function_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_name([NotNull] SQLiteParser.Function_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.schema_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchema_name([NotNull] SQLiteParser.Schema_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.schema_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchema_name([NotNull] SQLiteParser.Schema_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_name([NotNull] SQLiteParser.Table_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_name([NotNull] SQLiteParser.Table_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.table_or_index_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_or_index_name([NotNull] SQLiteParser.Table_or_index_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.table_or_index_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_or_index_name([NotNull] SQLiteParser.Table_or_index_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.column_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_name([NotNull] SQLiteParser.Column_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.column_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_name([NotNull] SQLiteParser.Column_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.column_name_excluding_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_name_excluding_string([NotNull] SQLiteParser.Column_name_excluding_stringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.column_name_excluding_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_name_excluding_string([NotNull] SQLiteParser.Column_name_excluding_stringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.column_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_alias([NotNull] SQLiteParser.Column_aliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.column_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_alias([NotNull] SQLiteParser.Column_aliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.collation_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollation_name([NotNull] SQLiteParser.Collation_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.collation_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollation_name([NotNull] SQLiteParser.Collation_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.foreign_table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeign_table([NotNull] SQLiteParser.Foreign_tableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.foreign_table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeign_table([NotNull] SQLiteParser.Foreign_tableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.index_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex_name([NotNull] SQLiteParser.Index_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.index_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex_name([NotNull] SQLiteParser.Index_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.trigger_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrigger_name([NotNull] SQLiteParser.Trigger_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.trigger_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrigger_name([NotNull] SQLiteParser.Trigger_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.view_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterView_name([NotNull] SQLiteParser.View_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.view_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitView_name([NotNull] SQLiteParser.View_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.module_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule_name([NotNull] SQLiteParser.Module_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.module_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule_name([NotNull] SQLiteParser.Module_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.pragma_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragma_name([NotNull] SQLiteParser.Pragma_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.pragma_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragma_name([NotNull] SQLiteParser.Pragma_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.savepoint_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSavepoint_name([NotNull] SQLiteParser.Savepoint_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.savepoint_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSavepoint_name([NotNull] SQLiteParser.Savepoint_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.table_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_alias([NotNull] SQLiteParser.Table_aliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.table_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_alias([NotNull] SQLiteParser.Table_aliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.table_alias_excluding_joins"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_alias_excluding_joins([NotNull] SQLiteParser.Table_alias_excluding_joinsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.table_alias_excluding_joins"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_alias_excluding_joins([NotNull] SQLiteParser.Table_alias_excluding_joinsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.window_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWindow_name([NotNull] SQLiteParser.Window_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.window_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWindow_name([NotNull] SQLiteParser.Window_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlias([NotNull] SQLiteParser.AliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlias([NotNull] SQLiteParser.AliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.base_window_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBase_window_name([NotNull] SQLiteParser.Base_window_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.base_window_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBase_window_name([NotNull] SQLiteParser.Base_window_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.table_function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_function_name([NotNull] SQLiteParser.Table_function_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.table_function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_function_name([NotNull] SQLiteParser.Table_function_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.any_name_excluding_raise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAny_name_excluding_raise([NotNull] SQLiteParser.Any_name_excluding_raiseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.any_name_excluding_raise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAny_name_excluding_raise([NotNull] SQLiteParser.Any_name_excluding_raiseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.any_name_excluding_joins"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAny_name_excluding_joins([NotNull] SQLiteParser.Any_name_excluding_joinsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.any_name_excluding_joins"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAny_name_excluding_joins([NotNull] SQLiteParser.Any_name_excluding_joinsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.any_name_excluding_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAny_name_excluding_string([NotNull] SQLiteParser.Any_name_excluding_stringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.any_name_excluding_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAny_name_excluding_string([NotNull] SQLiteParser.Any_name_excluding_stringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLiteParser.any_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAny_name([NotNull] SQLiteParser.Any_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLiteParser.any_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAny_name([NotNull] SQLiteParser.Any_nameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Antlr4C3.Demo.Grammar
