//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Whitebox.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Antlr4C3.Grammars {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="WhiteboxParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IWhiteboxListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.test1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest1([NotNull] WhiteboxParser.Test1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.test1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest1([NotNull] WhiteboxParser.Test1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule1([NotNull] WhiteboxParser.Rule1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule1([NotNull] WhiteboxParser.Rule1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule2([NotNull] WhiteboxParser.Rule2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule2([NotNull] WhiteboxParser.Rule2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule3([NotNull] WhiteboxParser.Rule3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule3([NotNull] WhiteboxParser.Rule3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule4([NotNull] WhiteboxParser.Rule4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule4([NotNull] WhiteboxParser.Rule4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule5([NotNull] WhiteboxParser.Rule5Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule5([NotNull] WhiteboxParser.Rule5Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.test2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest2([NotNull] WhiteboxParser.Test2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.test2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest2([NotNull] WhiteboxParser.Test2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule7([NotNull] WhiteboxParser.Rule7Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule7([NotNull] WhiteboxParser.Rule7Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule8([NotNull] WhiteboxParser.Rule8Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule8([NotNull] WhiteboxParser.Rule8Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule9"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule9([NotNull] WhiteboxParser.Rule9Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule9"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule9([NotNull] WhiteboxParser.Rule9Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule10"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule10([NotNull] WhiteboxParser.Rule10Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule10"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule10([NotNull] WhiteboxParser.Rule10Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule11"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule11([NotNull] WhiteboxParser.Rule11Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule11"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule11([NotNull] WhiteboxParser.Rule11Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.test3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest3([NotNull] WhiteboxParser.Test3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.test3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest3([NotNull] WhiteboxParser.Test3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule13"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule13([NotNull] WhiteboxParser.Rule13Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule13"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule13([NotNull] WhiteboxParser.Rule13Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.test4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest4([NotNull] WhiteboxParser.Test4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.test4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest4([NotNull] WhiteboxParser.Test4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule15"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule15([NotNull] WhiteboxParser.Rule15Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule15"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule15([NotNull] WhiteboxParser.Rule15Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule16([NotNull] WhiteboxParser.Rule16Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule16([NotNull] WhiteboxParser.Rule16Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.test5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest5([NotNull] WhiteboxParser.Test5Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.test5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest5([NotNull] WhiteboxParser.Test5Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule18"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule18([NotNull] WhiteboxParser.Rule18Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule18"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule18([NotNull] WhiteboxParser.Rule18Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule19"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule19([NotNull] WhiteboxParser.Rule19Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule19"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule19([NotNull] WhiteboxParser.Rule19Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.test6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest6([NotNull] WhiteboxParser.Test6Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.test6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest6([NotNull] WhiteboxParser.Test6Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule21"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule21([NotNull] WhiteboxParser.Rule21Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule21"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule21([NotNull] WhiteboxParser.Rule21Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.rule22"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule22([NotNull] WhiteboxParser.Rule22Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.rule22"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule22([NotNull] WhiteboxParser.Rule22Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.test7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest7([NotNull] WhiteboxParser.Test7Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.test7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest7([NotNull] WhiteboxParser.Test7Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WhiteboxParser.test8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest8([NotNull] WhiteboxParser.Test8Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WhiteboxParser.test8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest8([NotNull] WhiteboxParser.Test8Context context);
}
} // namespace Antlr4C3.Grammars
