//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Whitebox.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Antlr4C3.Tests.Grammar {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class WhiteboxParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LOREM=1, IPSUM=2, DOLOR=3, SIT=4, AMET=5, CONSECTETUR=6, ADIPISCING=7, 
		WS=8;
	public const int
		RULE_test1 = 0, RULE_rule1 = 1, RULE_rule2 = 2, RULE_rule3 = 3, RULE_rule4 = 4, 
		RULE_rule5 = 5, RULE_test2 = 6, RULE_rule7 = 7, RULE_rule8 = 8, RULE_rule9 = 9, 
		RULE_rule10 = 10, RULE_rule11 = 11, RULE_test3 = 12, RULE_rule13 = 13, 
		RULE_test4 = 14, RULE_rule15 = 15, RULE_rule16 = 16, RULE_test5 = 17, 
		RULE_rule18 = 18, RULE_rule19 = 19, RULE_test6 = 20, RULE_rule21 = 21, 
		RULE_rule22 = 22, RULE_test7 = 23, RULE_test8 = 24;
	public static readonly string[] ruleNames = {
		"test1", "rule1", "rule2", "rule3", "rule4", "rule5", "test2", "rule7", 
		"rule8", "rule9", "rule10", "rule11", "test3", "rule13", "test4", "rule15", 
		"rule16", "test5", "rule18", "rule19", "test6", "rule21", "rule22", "test7", 
		"test8"
	};

	private static readonly string[] _LiteralNames = {
		null, "'LOREM'", "'IPSUM'", "'DOLOR'", "'SIT'", "'AMET'", "'CONSECTETUR'", 
		"'ADIPISCING'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LOREM", "IPSUM", "DOLOR", "SIT", "AMET", "CONSECTETUR", "ADIPISCING", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Whitebox.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static WhiteboxParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public WhiteboxParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public WhiteboxParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Test1Context : ParserRuleContext {
		public Rule1Context rule1() {
			return GetRuleContext<Rule1Context>(0);
		}
		public ITerminalNode ADIPISCING() { return GetToken(WhiteboxParser.ADIPISCING, 0); }
		public Test1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_test1; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterTest1(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitTest1(this);
		}
	}

	[RuleVersion(0)]
	public Test1Context test1() {
		Test1Context _localctx = new Test1Context(Context, State);
		EnterRule(_localctx, 0, RULE_test1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50; rule1();
			State = 51; Match(ADIPISCING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule1Context : ParserRuleContext {
		public Rule2Context rule2() {
			return GetRuleContext<Rule2Context>(0);
		}
		public ITerminalNode CONSECTETUR() { return GetToken(WhiteboxParser.CONSECTETUR, 0); }
		public Rule1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule1; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule1(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule1(this);
		}
	}

	[RuleVersion(0)]
	public Rule1Context rule1() {
		Rule1Context _localctx = new Rule1Context(Context, State);
		EnterRule(_localctx, 2, RULE_rule1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53; rule2();
			State = 54; Match(CONSECTETUR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule2Context : ParserRuleContext {
		public ITerminalNode LOREM() { return GetToken(WhiteboxParser.LOREM, 0); }
		public Rule3Context rule3() {
			return GetRuleContext<Rule3Context>(0);
		}
		public Rule5Context rule5() {
			return GetRuleContext<Rule5Context>(0);
		}
		public ITerminalNode[] SIT() { return GetTokens(WhiteboxParser.SIT); }
		public ITerminalNode SIT(int i) {
			return GetToken(WhiteboxParser.SIT, i);
		}
		public ITerminalNode AMET() { return GetToken(WhiteboxParser.AMET, 0); }
		public Rule2Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule2; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule2(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule2(this);
		}
	}

	[RuleVersion(0)]
	public Rule2Context rule2() {
		Rule2Context _localctx = new Rule2Context(Context, State);
		EnterRule(_localctx, 4, RULE_rule2);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 56; Match(LOREM);
			State = 57; rule3();
			State = 58; rule5();
			State = 62;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SIT) {
				{
				{
				State = 59; Match(SIT);
				}
				}
				State = 64;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 66;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==AMET) {
				{
				State = 65; Match(AMET);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule3Context : ParserRuleContext {
		public Rule4Context rule4() {
			return GetRuleContext<Rule4Context>(0);
		}
		public ITerminalNode DOLOR() { return GetToken(WhiteboxParser.DOLOR, 0); }
		public Rule3Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule3; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule3(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule3(this);
		}
	}

	[RuleVersion(0)]
	public Rule3Context rule3() {
		Rule3Context _localctx = new Rule3Context(Context, State);
		EnterRule(_localctx, 6, RULE_rule3);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68; rule4();
			State = 70;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DOLOR) {
				{
				State = 69; Match(DOLOR);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule4Context : ParserRuleContext {
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public Rule4Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule4; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule4(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule4(this);
		}
	}

	[RuleVersion(0)]
	public Rule4Context rule4() {
		Rule4Context _localctx = new Rule4Context(Context, State);
		EnterRule(_localctx, 8, RULE_rule4);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 73;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IPSUM) {
				{
				State = 72; Match(IPSUM);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule5Context : ParserRuleContext {
		public Rule5Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule5; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule5(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule5(this);
		}
	}

	[RuleVersion(0)]
	public Rule5Context rule5() {
		Rule5Context _localctx = new Rule5Context(Context, State);
		EnterRule(_localctx, 10, RULE_rule5);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Test2Context : ParserRuleContext {
		public Rule7Context rule7() {
			return GetRuleContext<Rule7Context>(0);
		}
		public ITerminalNode ADIPISCING() { return GetToken(WhiteboxParser.ADIPISCING, 0); }
		public Test2Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_test2; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterTest2(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitTest2(this);
		}
	}

	[RuleVersion(0)]
	public Test2Context test2() {
		Test2Context _localctx = new Test2Context(Context, State);
		EnterRule(_localctx, 12, RULE_test2);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77; rule7();
			State = 78; Match(ADIPISCING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule7Context : ParserRuleContext {
		public Rule8Context rule8() {
			return GetRuleContext<Rule8Context>(0);
		}
		public ITerminalNode CONSECTETUR() { return GetToken(WhiteboxParser.CONSECTETUR, 0); }
		public Rule7Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule7; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule7(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule7(this);
		}
	}

	[RuleVersion(0)]
	public Rule7Context rule7() {
		Rule7Context _localctx = new Rule7Context(Context, State);
		EnterRule(_localctx, 14, RULE_rule7);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80; rule8();
			State = 81; Match(CONSECTETUR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule8Context : ParserRuleContext {
		public ITerminalNode LOREM() { return GetToken(WhiteboxParser.LOREM, 0); }
		public Rule11Context rule11() {
			return GetRuleContext<Rule11Context>(0);
		}
		public Rule9Context rule9() {
			return GetRuleContext<Rule9Context>(0);
		}
		public ITerminalNode[] SIT() { return GetTokens(WhiteboxParser.SIT); }
		public ITerminalNode SIT(int i) {
			return GetToken(WhiteboxParser.SIT, i);
		}
		public ITerminalNode AMET() { return GetToken(WhiteboxParser.AMET, 0); }
		public Rule8Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule8; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule8(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule8(this);
		}
	}

	[RuleVersion(0)]
	public Rule8Context rule8() {
		Rule8Context _localctx = new Rule8Context(Context, State);
		EnterRule(_localctx, 16, RULE_rule8);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83; Match(LOREM);
			State = 84; rule11();
			State = 85; rule9();
			State = 89;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SIT) {
				{
				{
				State = 86; Match(SIT);
				}
				}
				State = 91;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 93;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==AMET) {
				{
				State = 92; Match(AMET);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule9Context : ParserRuleContext {
		public Rule10Context rule10() {
			return GetRuleContext<Rule10Context>(0);
		}
		public ITerminalNode DOLOR() { return GetToken(WhiteboxParser.DOLOR, 0); }
		public Rule9Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule9; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule9(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule9(this);
		}
	}

	[RuleVersion(0)]
	public Rule9Context rule9() {
		Rule9Context _localctx = new Rule9Context(Context, State);
		EnterRule(_localctx, 18, RULE_rule9);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95; rule10();
			State = 97;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DOLOR) {
				{
				State = 96; Match(DOLOR);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule10Context : ParserRuleContext {
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public Rule10Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule10; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule10(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule10(this);
		}
	}

	[RuleVersion(0)]
	public Rule10Context rule10() {
		Rule10Context _localctx = new Rule10Context(Context, State);
		EnterRule(_localctx, 20, RULE_rule10);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IPSUM) {
				{
				State = 99; Match(IPSUM);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule11Context : ParserRuleContext {
		public Rule11Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule11; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule11(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule11(this);
		}
	}

	[RuleVersion(0)]
	public Rule11Context rule11() {
		Rule11Context _localctx = new Rule11Context(Context, State);
		EnterRule(_localctx, 22, RULE_rule11);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Test3Context : ParserRuleContext {
		public ITerminalNode LOREM() { return GetToken(WhiteboxParser.LOREM, 0); }
		public Rule13Context rule13() {
			return GetRuleContext<Rule13Context>(0);
		}
		public ITerminalNode CONSECTETUR() { return GetToken(WhiteboxParser.CONSECTETUR, 0); }
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public ITerminalNode[] AMET() { return GetTokens(WhiteboxParser.AMET); }
		public ITerminalNode AMET(int i) {
			return GetToken(WhiteboxParser.AMET, i);
		}
		public Test3Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_test3; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterTest3(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitTest3(this);
		}
	}

	[RuleVersion(0)]
	public Test3Context test3() {
		Test3Context _localctx = new Test3Context(Context, State);
		EnterRule(_localctx, 24, RULE_test3);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104; Match(LOREM);
			State = 106;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IPSUM) {
				{
				State = 105; Match(IPSUM);
				}
			}

			State = 108; rule13();
			State = 110;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 109; Match(AMET);
				}
				}
				State = 112;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==AMET );
			State = 114; Match(CONSECTETUR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule13Context : ParserRuleContext {
		public ITerminalNode[] DOLOR() { return GetTokens(WhiteboxParser.DOLOR); }
		public ITerminalNode DOLOR(int i) {
			return GetToken(WhiteboxParser.DOLOR, i);
		}
		public ITerminalNode[] SIT() { return GetTokens(WhiteboxParser.SIT); }
		public ITerminalNode SIT(int i) {
			return GetToken(WhiteboxParser.SIT, i);
		}
		public Rule13Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule13; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule13(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule13(this);
		}
	}

	[RuleVersion(0)]
	public Rule13Context rule13() {
		Rule13Context _localctx = new Rule13Context(Context, State);
		EnterRule(_localctx, 26, RULE_rule13);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DOLOR || _la==SIT) {
				{
				{
				State = 116;
				_la = TokenStream.LA(1);
				if ( !(_la==DOLOR || _la==SIT) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 121;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Test4Context : ParserRuleContext {
		public ITerminalNode LOREM() { return GetToken(WhiteboxParser.LOREM, 0); }
		public Rule15Context rule15() {
			return GetRuleContext<Rule15Context>(0);
		}
		public Rule16Context rule16() {
			return GetRuleContext<Rule16Context>(0);
		}
		public Test4Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_test4; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterTest4(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitTest4(this);
		}
	}

	[RuleVersion(0)]
	public Test4Context test4() {
		Test4Context _localctx = new Test4Context(Context, State);
		EnterRule(_localctx, 28, RULE_test4);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 122; Match(LOREM);
			State = 125;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				{
				State = 123; rule15();
				}
				break;
			case 2:
				{
				State = 124; rule16();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule15Context : ParserRuleContext {
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public ITerminalNode DOLOR() { return GetToken(WhiteboxParser.DOLOR, 0); }
		public ITerminalNode SIT() { return GetToken(WhiteboxParser.SIT, 0); }
		public Rule15Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule15; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule15(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule15(this);
		}
	}

	[RuleVersion(0)]
	public Rule15Context rule15() {
		Rule15Context _localctx = new Rule15Context(Context, State);
		EnterRule(_localctx, 30, RULE_rule15);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127; Match(IPSUM);
			State = 128; Match(DOLOR);
			State = 129; Match(SIT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule16Context : ParserRuleContext {
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public ITerminalNode DOLOR() { return GetToken(WhiteboxParser.DOLOR, 0); }
		public ITerminalNode AMET() { return GetToken(WhiteboxParser.AMET, 0); }
		public Rule16Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule16; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule16(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule16(this);
		}
	}

	[RuleVersion(0)]
	public Rule16Context rule16() {
		Rule16Context _localctx = new Rule16Context(Context, State);
		EnterRule(_localctx, 32, RULE_rule16);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 131; Match(IPSUM);
			State = 132; Match(DOLOR);
			State = 133; Match(AMET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Test5Context : ParserRuleContext {
		public ITerminalNode LOREM() { return GetToken(WhiteboxParser.LOREM, 0); }
		public Rule15Context rule15() {
			return GetRuleContext<Rule15Context>(0);
		}
		public Rule16Context rule16() {
			return GetRuleContext<Rule16Context>(0);
		}
		public Test5Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_test5; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterTest5(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitTest5(this);
		}
	}

	[RuleVersion(0)]
	public Test5Context test5() {
		Test5Context _localctx = new Test5Context(Context, State);
		EnterRule(_localctx, 34, RULE_test5);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135; Match(LOREM);
			State = 138;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				{
				State = 136; rule15();
				}
				break;
			case 2:
				{
				State = 137; rule16();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule18Context : ParserRuleContext {
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public ITerminalNode DOLOR() { return GetToken(WhiteboxParser.DOLOR, 0); }
		public ITerminalNode SIT() { return GetToken(WhiteboxParser.SIT, 0); }
		public ITerminalNode CONSECTETUR() { return GetToken(WhiteboxParser.CONSECTETUR, 0); }
		public Rule18Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule18; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule18(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule18(this);
		}
	}

	[RuleVersion(0)]
	public Rule18Context rule18() {
		Rule18Context _localctx = new Rule18Context(Context, State);
		EnterRule(_localctx, 36, RULE_rule18);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140; Match(IPSUM);
			State = 141; Match(DOLOR);
			State = 142;
			_la = TokenStream.LA(1);
			if ( !(_la==SIT || _la==CONSECTETUR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule19Context : ParserRuleContext {
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public ITerminalNode DOLOR() { return GetToken(WhiteboxParser.DOLOR, 0); }
		public ITerminalNode AMET() { return GetToken(WhiteboxParser.AMET, 0); }
		public Rule19Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule19; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule19(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule19(this);
		}
	}

	[RuleVersion(0)]
	public Rule19Context rule19() {
		Rule19Context _localctx = new Rule19Context(Context, State);
		EnterRule(_localctx, 38, RULE_rule19);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 144; Match(IPSUM);
			State = 145; Match(DOLOR);
			State = 146; Match(AMET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Test6Context : ParserRuleContext {
		public ITerminalNode LOREM() { return GetToken(WhiteboxParser.LOREM, 0); }
		public Rule15Context rule15() {
			return GetRuleContext<Rule15Context>(0);
		}
		public Rule16Context rule16() {
			return GetRuleContext<Rule16Context>(0);
		}
		public Test6Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_test6; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterTest6(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitTest6(this);
		}
	}

	[RuleVersion(0)]
	public Test6Context test6() {
		Test6Context _localctx = new Test6Context(Context, State);
		EnterRule(_localctx, 40, RULE_test6);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 148; Match(LOREM);
			State = 151;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 149; rule15();
				}
				break;
			case 2:
				{
				State = 150; rule16();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule21Context : ParserRuleContext {
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public ITerminalNode DOLOR() { return GetToken(WhiteboxParser.DOLOR, 0); }
		public ITerminalNode SIT() { return GetToken(WhiteboxParser.SIT, 0); }
		public Rule21Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule21; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule21(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule21(this);
		}
	}

	[RuleVersion(0)]
	public Rule21Context rule21() {
		Rule21Context _localctx = new Rule21Context(Context, State);
		EnterRule(_localctx, 42, RULE_rule21);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153; Match(IPSUM);
			State = 154; Match(DOLOR);
			State = 155; Match(SIT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rule22Context : ParserRuleContext {
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public ITerminalNode DOLOR() { return GetToken(WhiteboxParser.DOLOR, 0); }
		public ITerminalNode AMET() { return GetToken(WhiteboxParser.AMET, 0); }
		public ITerminalNode CONSECTETUR() { return GetToken(WhiteboxParser.CONSECTETUR, 0); }
		public Rule22Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rule22; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterRule22(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitRule22(this);
		}
	}

	[RuleVersion(0)]
	public Rule22Context rule22() {
		Rule22Context _localctx = new Rule22Context(Context, State);
		EnterRule(_localctx, 44, RULE_rule22);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 157; Match(IPSUM);
			State = 158; Match(DOLOR);
			State = 159;
			_la = TokenStream.LA(1);
			if ( !(_la==AMET || _la==CONSECTETUR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Test7Context : ParserRuleContext {
		public ITerminalNode LOREM() { return GetToken(WhiteboxParser.LOREM, 0); }
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public ITerminalNode DOLOR() { return GetToken(WhiteboxParser.DOLOR, 0); }
		public ITerminalNode SIT() { return GetToken(WhiteboxParser.SIT, 0); }
		public ITerminalNode AMET() { return GetToken(WhiteboxParser.AMET, 0); }
		public Test7Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_test7; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterTest7(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitTest7(this);
		}
	}

	[RuleVersion(0)]
	public Test7Context test7() {
		Test7Context _localctx = new Test7Context(Context, State);
		EnterRule(_localctx, 46, RULE_test7);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 161; Match(LOREM);
			State = 168;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				{
				State = 162; Match(IPSUM);
				State = 163; Match(DOLOR);
				State = 164; Match(SIT);
				}
				break;
			case 2:
				{
				State = 165; Match(IPSUM);
				State = 166; Match(DOLOR);
				State = 167; Match(AMET);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Test8Context : ParserRuleContext {
		public ITerminalNode LOREM() { return GetToken(WhiteboxParser.LOREM, 0); }
		public ITerminalNode IPSUM() { return GetToken(WhiteboxParser.IPSUM, 0); }
		public ITerminalNode DOLOR() { return GetToken(WhiteboxParser.DOLOR, 0); }
		public ITerminalNode SIT() { return GetToken(WhiteboxParser.SIT, 0); }
		public ITerminalNode AMET() { return GetToken(WhiteboxParser.AMET, 0); }
		public ITerminalNode CONSECTETUR() { return GetToken(WhiteboxParser.CONSECTETUR, 0); }
		public Test8Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_test8; } }
		public override void EnterRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.EnterTest8(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IWhiteboxListener typedListener = listener as IWhiteboxListener;
			if (typedListener != null) typedListener.ExitTest8(this);
		}
	}

	[RuleVersion(0)]
	public Test8Context test8() {
		Test8Context _localctx = new Test8Context(Context, State);
		EnterRule(_localctx, 48, RULE_test8);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 170; Match(LOREM);
			State = 179;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				{
				State = 171; Match(IPSUM);
				State = 172; Match(DOLOR);
				State = 173; Match(SIT);
				State = 174; Match(AMET);
				}
				break;
			case 2:
				{
				State = 175; Match(IPSUM);
				State = 176; Match(DOLOR);
				State = 177; Match(SIT);
				State = 178; Match(CONSECTETUR);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\n', '\xB8', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 
		'?', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x42', '\v', '\x4', '\x3', 
		'\x4', '\x5', '\x4', '\x45', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x5', '\x5', 'I', '\n', '\x5', '\x3', '\x6', '\x5', '\x6', 'L', '\n', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\a', '\n', 'Z', '\n', '\n', '\f', '\n', '\xE', '\n', 
		']', '\v', '\n', '\x3', '\n', '\x5', '\n', '`', '\n', '\n', '\x3', '\v', 
		'\x3', '\v', '\x5', '\v', '\x64', '\n', '\v', '\x3', '\f', '\x5', '\f', 
		'g', '\n', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', 
		'\x5', '\xE', 'm', '\n', '\xE', '\x3', '\xE', '\x3', '\xE', '\x6', '\xE', 
		'q', '\n', '\xE', '\r', '\xE', '\xE', '\xE', 'r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\a', '\xF', 'x', '\n', '\xF', '\f', '\xF', '\xE', 
		'\xF', '{', '\v', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x5', '\x10', '\x80', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\x8D', 
		'\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x5', '\x16', '\x9A', '\n', '\x16', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x5', 
		'\x19', '\xAB', '\n', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x5', '\x1A', '\xB6', '\n', '\x1A', '\x3', '\x1A', '\x2', 
		'\x2', '\x1B', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', 
		'*', ',', '.', '\x30', '\x32', '\x2', '\x5', '\x3', '\x2', '\x5', '\x6', 
		'\x4', '\x2', '\x6', '\x6', '\b', '\b', '\x3', '\x2', '\a', '\b', '\x2', 
		'\xAE', '\x2', '\x34', '\x3', '\x2', '\x2', '\x2', '\x4', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\x6', ':', '\x3', '\x2', '\x2', '\x2', '\b', '\x46', 
		'\x3', '\x2', '\x2', '\x2', '\n', 'K', '\x3', '\x2', '\x2', '\x2', '\f', 
		'M', '\x3', '\x2', '\x2', '\x2', '\xE', 'O', '\x3', '\x2', '\x2', '\x2', 
		'\x10', 'R', '\x3', '\x2', '\x2', '\x2', '\x12', 'U', '\x3', '\x2', '\x2', 
		'\x2', '\x14', '\x61', '\x3', '\x2', '\x2', '\x2', '\x16', '\x66', '\x3', 
		'\x2', '\x2', '\x2', '\x18', 'h', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'j', '\x3', '\x2', '\x2', '\x2', '\x1C', 'y', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', '|', '\x3', '\x2', '\x2', '\x2', ' ', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\"', '\x85', '\x3', '\x2', '\x2', '\x2', '$', '\x89', '\x3', '\x2', 
		'\x2', '\x2', '&', '\x8E', '\x3', '\x2', '\x2', '\x2', '(', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '*', '\x96', '\x3', '\x2', '\x2', '\x2', ',', '\x9B', 
		'\x3', '\x2', '\x2', '\x2', '.', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\x32', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\x34', '\x35', '\x5', '\x4', '\x3', '\x2', '\x35', '\x36', '\a', 
		'\t', '\x2', '\x2', '\x36', '\x3', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x38', '\x5', '\x6', '\x4', '\x2', '\x38', '\x39', '\a', '\b', '\x2', 
		'\x2', '\x39', '\x5', '\x3', '\x2', '\x2', '\x2', ':', ';', '\a', '\x3', 
		'\x2', '\x2', ';', '<', '\x5', '\b', '\x5', '\x2', '<', '@', '\x5', '\f', 
		'\a', '\x2', '=', '?', '\a', '\x6', '\x2', '\x2', '>', '=', '\x3', '\x2', 
		'\x2', '\x2', '?', '\x42', '\x3', '\x2', '\x2', '\x2', '@', '>', '\x3', 
		'\x2', '\x2', '\x2', '@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\x42', '@', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\x45', '\a', '\a', '\x2', '\x2', '\x44', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x45', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x46', 'H', '\x5', '\n', '\x6', '\x2', 
		'G', 'I', '\a', '\x5', '\x2', '\x2', 'H', 'G', '\x3', '\x2', '\x2', '\x2', 
		'H', 'I', '\x3', '\x2', '\x2', '\x2', 'I', '\t', '\x3', '\x2', '\x2', 
		'\x2', 'J', 'L', '\a', '\x4', '\x2', '\x2', 'K', 'J', '\x3', '\x2', '\x2', 
		'\x2', 'K', 'L', '\x3', '\x2', '\x2', '\x2', 'L', '\v', '\x3', '\x2', 
		'\x2', '\x2', 'M', 'N', '\x3', '\x2', '\x2', '\x2', 'N', '\r', '\x3', 
		'\x2', '\x2', '\x2', 'O', 'P', '\x5', '\x10', '\t', '\x2', 'P', 'Q', '\a', 
		'\t', '\x2', '\x2', 'Q', '\xF', '\x3', '\x2', '\x2', '\x2', 'R', 'S', 
		'\x5', '\x12', '\n', '\x2', 'S', 'T', '\a', '\b', '\x2', '\x2', 'T', '\x11', 
		'\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', '\x3', '\x2', '\x2', 'V', 
		'W', '\x5', '\x18', '\r', '\x2', 'W', '[', '\x5', '\x14', '\v', '\x2', 
		'X', 'Z', '\a', '\x6', '\x2', '\x2', 'Y', 'X', '\x3', '\x2', '\x2', '\x2', 
		'Z', ']', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', '_', '\x3', '\x2', '\x2', 
		'\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', '^', '`', '\a', '\a', '\x2', 
		'\x2', '_', '^', '\x3', '\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', '\x2', 
		'\x2', '`', '\x13', '\x3', '\x2', '\x2', '\x2', '\x61', '\x63', '\x5', 
		'\x16', '\f', '\x2', '\x62', '\x64', '\a', '\x5', '\x2', '\x2', '\x63', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\x15', '\x3', '\x2', '\x2', '\x2', '\x65', 'g', '\a', 
		'\x4', '\x2', '\x2', '\x66', '\x65', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'g', '\x3', '\x2', '\x2', '\x2', 'g', '\x17', '\x3', '\x2', '\x2', '\x2', 
		'h', 'i', '\x3', '\x2', '\x2', '\x2', 'i', '\x19', '\x3', '\x2', '\x2', 
		'\x2', 'j', 'l', '\a', '\x3', '\x2', '\x2', 'k', 'm', '\a', '\x4', '\x2', 
		'\x2', 'l', 'k', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\x3', '\x2', '\x2', 
		'\x2', 'm', 'n', '\x3', '\x2', '\x2', '\x2', 'n', 'p', '\x5', '\x1C', 
		'\xF', '\x2', 'o', 'q', '\a', '\a', '\x2', '\x2', 'p', 'o', '\x3', '\x2', 
		'\x2', '\x2', 'q', 'r', '\x3', '\x2', '\x2', '\x2', 'r', 'p', '\x3', '\x2', 
		'\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', '\x2', 
		'\x2', '\x2', 't', 'u', '\a', '\b', '\x2', '\x2', 'u', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', 'v', 'x', '\t', '\x2', '\x2', '\x2', 'w', 'v', '\x3', 
		'\x2', '\x2', '\x2', 'x', '{', '\x3', '\x2', '\x2', '\x2', 'y', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'y', 'z', '\x3', '\x2', '\x2', '\x2', 'z', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '{', 'y', '\x3', '\x2', '\x2', '\x2', '|', 
		'\x7F', '\a', '\x3', '\x2', '\x2', '}', '\x80', '\x5', ' ', '\x11', '\x2', 
		'~', '\x80', '\x5', '\"', '\x12', '\x2', '\x7F', '}', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '~', '\x3', '\x2', '\x2', '\x2', '\x80', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x81', '\x82', '\a', '\x4', '\x2', '\x2', '\x82', 
		'\x83', '\a', '\x5', '\x2', '\x2', '\x83', '\x84', '\a', '\x6', '\x2', 
		'\x2', '\x84', '!', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\a', 
		'\x4', '\x2', '\x2', '\x86', '\x87', '\a', '\x5', '\x2', '\x2', '\x87', 
		'\x88', '\a', '\a', '\x2', '\x2', '\x88', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x89', '\x8C', '\a', '\x3', '\x2', '\x2', '\x8A', '\x8D', '\x5', ' ', 
		'\x11', '\x2', '\x8B', '\x8D', '\x5', '\"', '\x12', '\x2', '\x8C', '\x8A', 
		'\x3', '\x2', '\x2', '\x2', '\x8C', '\x8B', '\x3', '\x2', '\x2', '\x2', 
		'\x8D', '%', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', '\x4', 
		'\x2', '\x2', '\x8F', '\x90', '\a', '\x5', '\x2', '\x2', '\x90', '\x91', 
		'\t', '\x3', '\x2', '\x2', '\x91', '\'', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x93', '\a', '\x4', '\x2', '\x2', '\x93', '\x94', '\a', '\x5', '\x2', 
		'\x2', '\x94', '\x95', '\a', '\a', '\x2', '\x2', '\x95', ')', '\x3', '\x2', 
		'\x2', '\x2', '\x96', '\x99', '\a', '\x3', '\x2', '\x2', '\x97', '\x9A', 
		'\x5', ' ', '\x11', '\x2', '\x98', '\x9A', '\x5', '\"', '\x12', '\x2', 
		'\x99', '\x97', '\x3', '\x2', '\x2', '\x2', '\x99', '\x98', '\x3', '\x2', 
		'\x2', '\x2', '\x9A', '+', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', 
		'\a', '\x4', '\x2', '\x2', '\x9C', '\x9D', '\a', '\x5', '\x2', '\x2', 
		'\x9D', '\x9E', '\a', '\x6', '\x2', '\x2', '\x9E', '-', '\x3', '\x2', 
		'\x2', '\x2', '\x9F', '\xA0', '\a', '\x4', '\x2', '\x2', '\xA0', '\xA1', 
		'\a', '\x5', '\x2', '\x2', '\xA1', '\xA2', '\t', '\x4', '\x2', '\x2', 
		'\xA2', '/', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xAA', '\a', '\x3', 
		'\x2', '\x2', '\xA4', '\xA5', '\a', '\x4', '\x2', '\x2', '\xA5', '\xA6', 
		'\a', '\x5', '\x2', '\x2', '\xA6', '\xAB', '\a', '\x6', '\x2', '\x2', 
		'\xA7', '\xA8', '\a', '\x4', '\x2', '\x2', '\xA8', '\xA9', '\a', '\x5', 
		'\x2', '\x2', '\xA9', '\xAB', '\a', '\a', '\x2', '\x2', '\xAA', '\xA4', 
		'\x3', '\x2', '\x2', '\x2', '\xAA', '\xA7', '\x3', '\x2', '\x2', '\x2', 
		'\xAB', '\x31', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xB5', '\a', '\x3', 
		'\x2', '\x2', '\xAD', '\xAE', '\a', '\x4', '\x2', '\x2', '\xAE', '\xAF', 
		'\a', '\x5', '\x2', '\x2', '\xAF', '\xB0', '\a', '\x6', '\x2', '\x2', 
		'\xB0', '\xB6', '\a', '\a', '\x2', '\x2', '\xB1', '\xB2', '\a', '\x4', 
		'\x2', '\x2', '\xB2', '\xB3', '\a', '\x5', '\x2', '\x2', '\xB3', '\xB4', 
		'\a', '\x6', '\x2', '\x2', '\xB4', '\xB6', '\a', '\b', '\x2', '\x2', '\xB5', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\x33', '\x3', '\x2', '\x2', '\x2', '\x12', '@', '\x44', 
		'H', 'K', '[', '_', '\x63', '\x66', 'l', 'r', 'y', '\x7F', '\x8C', '\x99', 
		'\xAA', '\xB5',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Antlr4C3.Tests.Grammar
